### ISSUE TITLE
Should use doc comments

### ISSUE THREAD

**Issue by srawlins** [dart-lang/benchmark_harness#28]
This is copied from [dartlang.org's #886](https://github.com/dart-lang/dartlang.org/issues/886):

From messick@google.com on June 10, 2014 19:42:51

> The benchmark_harness package doesn't use doc comments, only simple // comments (see benchmark_base.dart)

_Original issue: http://code.google.com/p/dart/issues/detail?id=19344_

**Comment by devoncarew** [comment]
This has been addressed.
