### ISSUE TITLE
Add AsyncBenchmarkBase

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/benchmark_harness#31]
I would possibly be willing to do this, assuming people are on board with the change.

**Comment by lukepighetti** [comment]
Looks like this issue is six years old now. I think we might just have to make a PR and go from there.

**Comment by vaind** [comment]
Hope it's fine to post this here, if not, please remove....

I've been missing some features in benchmark_harness as well, which led me to develop an alternative. After having it in-code in some projects, I've now decided to publish it for others, check out https://pub.dev/packages/benchmarking

**Comment by fzyzcjy** [comment]
+1 after 8 years...
